---
#- name: update_APT_package_cache
#  apt: update_cache=yes
 
- name: Install_basic_tools
  apt: pkg={{item}} state=installed force=yes
  sudo: yes
  tags:
  - install_basic
  with_items:
    - mc
    - htop
    - iptraf-ng
    - iotop 
    - lsof 
    - nmap 
    - nc
